version: '3.10.4'

# Definición de 2 servicios
services:

  web:
    image: python:3.10.10-alpine3.17 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - sqlite3
  
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db:/root/db/
